Attribute VB_Name = "ParamDefs"
'This module was generated by CLASSter (tm)
'from Urfin Jus. Copyright 2000-2002, All rights reserved.
'   CLASSter Version: Version 2.0 (2.0.130), Full Edition
'   Date: 16 Apr 2002, 09:43 
'   Connection string used:
'     "Provider=SQLOLEDB.1;Password=loopa4$;Persist Security Info=True;User ID=sa;Initial Catalog=Northwind;Data Source=acdc"
'   Dependencies: None
'
'   These constants may be used in calls to ExecSPbyName method of
'   database class. They contain packed attributes of stored procedures
'   parameters. ExecSPbyName method uses them to rebuild parameters
'   collection on-the-fly.
'   Examples:  DBClass.ExecSP SP_CUSTORDERSDETAIL, PRM_CUSTORDERSDETAIL, OrderID
'              DBClass.ExecSP SP_GETORDERS, PRM_GETORDERS, Array(FromDate, ToDate)
'

Public Const SP_CUSTORDERHIST = "[CustOrderHist]"
Public Const PRM_CUSTORDERHIST = "@CustomerID,202,1,5,0"

Public Const SP_CUSTORDERSDETAIL = "[CustOrdersDetail]"
Public Const PRM_CUSTORDERSDETAIL = "@OrderID,3,1,0,0"

Public Const SP_CUSTORDERSORDERS = "[CustOrdersOrders]"
Public Const PRM_CUSTORDERSORDERS = "@CustomerID,202,1,5,0"

Public Const SP_EMPLOYEE_SALES_BY_COUNTRY = "[Employee Sales by Country]"
Public Const PRM_EMPLOYEE_SALES_BY_COUNTRY = "@Beginning_Date,135,1,0,0;@Ending_Date,135,1,0,0"

Public Const SP_SALES_BY_YEAR = "[Sales by Year]"
Public Const PRM_SALES_BY_YEAR = "@Beginning_Date,135,1,0,0;@Ending_Date,135,1,0,0"

Public Const SP_SALESBYCATEGORY = "[SalesByCategory]"
Public Const PRM_SALESBYCATEGORY = "@CategoryName,202,1,15,0;@OrdYear,202,1,4,0"

Public Const SP_TEN_MOST_EXPENSIVE_PRODUCTS = "[Ten Most Expensive Products]"
Public Const PRM_TEN_MOST_EXPENSIVE_PRODUCTS = ""
